### ISSUE TITLE
Pickle data full_sims_fast_random_raster.pkl

### ISSUE THREAD

**Issue by hududed** [saugatkandel/fast_smart_scanning#2]
was trying to reproduce some things from the paper in `comparisons_full.ipynb`
The pickle file `full_sims_fast_random_raster.pkl` was missing.

Tried to reproduce that pickle file by running `simulate_full.ipynb` but got into the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 86
     84 sample_grid.measurement_interface.finalize_external_measurement(ground[grid[:,0], grid[:,1]])
     85 sample_grid.perform_measurements(grid)
---> 86 sample_grid.reconstruct_and_compute_erd()
     88 recons_this = sample_grid.recon_image.copy() [/](https://file+.vscode-resource.vscode-cdn.net/) sample_grid.recon_image.max() * sample_grid.measurement_info.unnormalized_values.max()
     89 recons_raster_all.append(recons_this)

File [~/miniconda3/envs/fast_test/lib/python3.10/site-packages/fast/core/base.py:185](https://file+.vscode-resource.vscode-cdn.net/home/hud/projects/fast_smart_scanning/work_directory/sims_paper/~/miniconda3/envs/fast_test/lib/python3.10/site-packages/fast/core/base.py:185), in Sample.reconstruct_and_compute_erd(self)
    182 self.recon_image = compute_recon(self.recon_image, measurement_info, self.neighbors)
    184 if self.params_erd.model_type == "slads-net":
--> 185     self.poly_features = compute_poly_features(
    186         self.params_sample,
    187         self.recon_image,
    188         unmeasured_idxs,
    189         self.neighbors,
    190         self.params_erd.feat_distance_cutoff,
    191         self.params_erd.feature_type,
    192     )
    194 # Compute RD/ERD; if every location has been scanned all positions are zero
    195 # Determine the Estimated Reduction in Distortion
    197 if len(measurement_info.unmeasured_idxs) == 0:

File [~/miniconda3/envs/fast_test/lib/python3.10/site-packages/fast/core/slads_features.py:64](https://file+.vscode-resource.vscode-cdn.net/home/hud/projects/fast_smart_scanning/work_directory/sims_paper/~/miniconda3/envs/fast_test/lib/python3.10/site-packages/fast/core/slads_features.py:64), in compute_poly_features(sample_params, recon_image, update_idxs, neighbors, feat_dist_cutoff, feat_type)
     61 feature = np.zeros((np.shape(update_idxs)[0], 6))
     63 # Compute std div features
---> 64 diff_vec = compute_difference(neighbors.values, np.tile(input_values, (neighbors.values.shape[1], 1)).T)
     65 feature[:, 0] = np.sum(neighbors.weights * diff_vec, axis=1)
     66 feature[:, 1] = np.sqrt(np.sum(np.power(diff_vec, 2), axis=1))

AttributeError: 'list' object has no attribute 'shape'
```

Is it possible to just share the pickle file?

**Comment by saugatkandel** [comment]
I didn't include the pickle files in the repository since they can get quite large. You have to run "simulate_full" and "simulate_fast" first to generate the pickle files. 

Unfortunately, I am not able to work on this until next week, so I cannot upload the files for now. I can do that next week.

**Comment by hududed** [comment]
Ok I will wait for it then thanks.

 But for this specific issue in `simulate_ful.ipynbl`:

 `diff_vec = compute_difference(neighbors.values, np.tile(input_values, (neighbors.values.shape[1], 1)).T)`

It seems like `neighbors.values` should be of type ndarray but is a list. Which is it?

**Comment by saugatkandel** [comment]
The issue you pointed out seems to be a bug in the code that only happens when the sampling reaches 100%.  It should work fine if you change the start of the while loop to:

``` python

stop_ratio = 0.99
n_scan_points = int(stop_ratio * ground.size)

while sample_fast.mask.sum() < n_scan_points:
    ...
```

The plotting code within this notebook is also problematic. That needs to be removed, so that the plotting happens only in the `comparisons_full` notebook. 


Thank you for pointing this out. I am currently on travel, so I will only be able to fix these next week.

**Comment by saugatkandel** [comment]
As a short term solution, setting the `stop_ratio` to `<100%` and disabling the plotting code in `simulate_full` should be sufficient. The plotting in `comparisons_full` works fine for me.

**Comment by hududed** [comment]
@saugatkandel apologies for the really late reply - it seems to run for now but not entirely sure where `stop_ratio` or `n_scan_points` is used in the while loop

**Comment by hududed** [comment]
The same error persists. The changes:

```
stop_ratio = 0.99
n_scan_points = int(stop_ratio * ground.size)

while sample_fast.mask.sum() < ground.size:
    sample_fast.measurement_interface.finalize_external_measurement(ground[new_idxs[:,0], new_idxs[:,1]])
    sample_fast.perform_measurements(new_idxs)
    sample_fast.reconstruct_and_compute_erd()
    new_idxs = sample_fast.find_new_measurement_idxs()
    
    count += 1
    if (count - 1) % 50 != 0:
        continue
        
        
    ratio = sample_fast.ratio_measured
    
    
    recons_fast_all.append(sample_fast.recon_image.copy())
    masks_fast_all.append(sample_fast.mask.copy())
    ratios_all.append(ratio)
    
    init_pattern = generate_scan_pattern(*ground.T.shape, num_scan_points = int(sample_fast.mask.sum()))
    sample_random = utils.create_experiment_sample(numx=ground.shape[1], numy=ground.shape[0],
                                      inner_batch_size=100,
                                      initial_idxs=init_pattern,
                                      stop_ratio=stop_ratio)
```

Basically added  `stop_ratio` at every `create_experiment_sample`. Not sure where to implement `n_scan_points`

**Comment by saugatkandel** [comment]
I should have clarified --- you need to change the beginning of that while loop, as shown here.

> The issue you pointed out seems to be a bug in the code that only happens when the sampling reaches 100%. It should work fine if you change the start of the while loop to:
> 
> ```python
> stop_ratio = 0.99
> n_scan_points = int(stop_ratio * ground.size)
> 
> while sample_fast.mask.sum() < n_scan_points:
>     ...
> ```
> 
> The plotting code within this notebook is also problematic. That needs to be removed, so that the plotting happens only in the `comparisons_full` notebook.
> 
> Thank you for pointing this out. I am currently on travel, so I will only be able to fix these next week.

**Comment by hududed** [comment]
My mistake! re-running, will update if all goes well

**Comment by hududed** [comment]
This works - closing this - thanks!

**Comment by saugatkandel** [comment]
Thank you for pointing this out. I added this temporary fix to the example notebook in the github.
